# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.box_check_update = false

  config.vm.network "public_network"

  config.vm.define "nginx" do |nginx|
    nginx.vm.hostname = "nginxtest"
    nginx.vm.network "forwarded_port", guest: 80, host: 8080
  end

  config.vm.define "psql" do |psql|
    psql.vm.hostname = "psql"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "512"
  end

end
